### ISSUE TITLE
Contaminated attempts to pull N2 and Oxygen out of the room

### ISSUE THREAD

**Issue by francinum** [DaedalusDock/Gameserver#73]
Reporting client version: 514.1589

## Round ID:
[58](https://scrubby.melonmesa.com/round/58)

## Testmerges:
- [Ungreebles the Floor [MDB IGNORE]](https://github.com/DaedalusDock/Gameserver/pull/61)
- [LORE PR](https://github.com/DaedalusDock/Gameserver/pull/59)
- [Dims lighting... again?](https://github.com/DaedalusDock/Gameserver/pull/68)
- [TEG REFORGED](https://github.com/DaedalusDock/Gameserver/pull/71)
- [Walls are now automatically named based on their consistutent materials](https://github.com/DaedalusDock/Gameserver/pull/69)
- [Vacuums now all act like space for heat exchange](https://github.com/DaedalusDock/Gameserver/pull/70)
- [Kapuconomy](https://github.com/DaedalusDock/Gameserver/pull/67)

## Reproduction:
```
set the air alarm of a room to contaminated
check what gasses the scrubbers are configured to scrub
```

Contaminated doesn't leave N2 and O2 in the air, likely due to weirdness involving the internal representation of gas types

**Comment by Kapu1178** [comment]
fixed in #77
